In [1]:
import pandas as pd
import numpy as np

data_E = pd.read_csv("dataQr/qrE.csv") 

point_E_top_left_board = (24.4, 5.6, 0.0)
side_size = 4.4
point_arm_starting = (20, -8, 0.0)

expected_top_left_board_x = point_E_top_left_board[0]
expected_top_left_board_y = point_E_top_left_board[1]

data_E["expected_top_left_board_x"] = expected_top_left_board_x
data_E["expected_top_left_board_y"] = expected_top_left_board_y
data_E["expected_bottom_left_board_x"] = expected_top_left_board_x
data_E["expected_bottom_left_board_y"] = expected_top_left_board_y + side_size
data_E["expected_top_right_board_x"] = expected_top_left_board_x - side_size
data_E["expected_top_right_board_y"] = expected_top_left_board_y
data_E["expected_bottom_right_board_x"] = expected_top_left_board_x - side_size
data_E["expected_bottom_right_board_y"] = expected_top_left_board_y + side_size

data_E["expected_top_left_board_z"] = point_E_top_left_board[2]
data_E["expected_bottom_left_board_z"] = point_E_top_left_board[2]
data_E["expected_top_right_board_z"] = point_E_top_left_board[2]
data_E["expected_bottom_right_board_z"] = point_E_top_left_board[2]

data_E["expected_center_board_x"] = expected_top_left_board_x - side_size/2
data_E["expected_center_board_y"] = expected_top_left_board_y + side_size/2
data_E["expected_center_board_z"] = point_E_top_left_board[2]

data_E["expected_center_arm_x"] = point_arm_starting[1] - (expected_top_left_board_y + side_size/2)
data_E["expected_center_arm_y"] = expected_top_left_board_x - side_size/2 - point_arm_starting[0]
data_E["expected_center_arm_z"] = point_arm_starting[2]

data_E.tail(5)

bottom_left_pixel_x  bottom_left_pixel_y  top_left_pixel_x  \
139            855.96400            215.62622         855.79755   
140            854.19050            214.64260         854.04596   
141            845.59485            205.62158         860.40350   
142            856.53516            216.66970         857.80480   
143            856.41235            216.42474         859.61786   

     top_left_pixel_y  top_right_pixel_x  top_right_pixel_y  \
139         352.41956          990.88007          348.49835   
140         354.32460          990.68085          347.86860   
141         346.44610          990.27216          348.59814   
142         349.66350          992.63070          349.93008   
143         348.27300          994.50550          352.21555   

     bottom_right_pixel_x  bottom_right_pixel_y  expected_top_left_board_x  \
139             996.25410             217.73766                       24.4   
140             994.66895             218.84343                       24.4   
141            1001.51030             214.19170                       24.4   
142             997.68130             217.14386                       24.4   
143             998.37915             216.33070                       24.4   

     expected_top_left_board_y          ...            \
139                        5.6          ...             
140                        5.6          ...             
141                        5.6          ...             
142                        5.6          ...             
143                        5.6          ...             

     expected_top_left_board_z  expected_bottom_left_board_z  \
139                        0.0                           0.0   
140                        0.0                           0.0   
141                        0.0                           0.0   
142                        0.0                           0.0   
143                        0.0                           0.0   

     expected_top_right_board_z  expected_bottom_right_board_z  \
139                         0.0                            0.0   
140                         0.0                            0.0   
141                         0.0                            0.0   
142                         0.0                            0.0   
143                         0.0                            0.0   

     expected_center_board_x  expected_center_board_y  \
139                     22.2                      7.8   
140                     22.2                      7.8   
141                     22.2                      7.8   
142                     22.2                      7.8   
143                     22.2                      7.8   

     expected_center_board_z  expected_center_arm_x  expected_center_arm_y  \
139                      0.0                  -15.8                    2.2   
140                      0.0                  -15.8                    2.2   
141                      0.0                  -15.8                    2.2   
142                      0.0                  -15.8                    2.2   
143                      0.0                  -15.8                    2.2   

     expected_center_arm_z  
139                    0.0  
140                    0.0  
141                    0.0  
142                    0.0  
143                    0.0  

[5 rows x 26 columns]

In [2]:
data_D = pd.read_csv("dataQr/qrD.csv") 

point_E_top_left_board = (4.4, 23.6, 0.0)
side_size = 4.4
point_arm_starting = (20, -8, 0.0)

expected_top_left_board_x = point_E_top_left_board[0]
expected_top_left_board_y = point_E_top_left_board[1]

data_D["expected_top_left_board_x"] = expected_top_left_board_x
data_D["expected_top_left_board_y"] = expected_top_left_board_y
data_D["expected_bottom_left_board_x"] = expected_top_left_board_x
data_D["expected_bottom_left_board_y"] = expected_top_left_board_y + side_size
data_D["expected_top_right_board_x"] = expected_top_left_board_x - side_size
data_D["expected_top_right_board_y"] = expected_top_left_board_y
data_D["expected_bottom_right_board_x"] = expected_top_left_board_x - side_size
data_D["expected_bottom_right_board_y"] = expected_top_left_board_y + side_size

data_D["expected_top_left_board_z"] = point_E_top_left_board[2]
data_D["expected_bottom_left_board_z"] = point_E_top_left_board[2]
data_D["expected_top_right_board_z"] = point_E_top_left_board[2]
data_D["expected_bottom_right_board_z"] = point_E_top_left_board[2]

data_D["expected_center_board_x"] = expected_top_left_board_x - side_size/2
data_D["expected_center_board_y"] = expected_top_left_board_y + side_size/2
data_D["expected_center_board_z"] = point_E_top_left_board[2]

data_D["expected_center_arm_x"] = point_arm_starting[1] - (expected_top_left_board_y + side_size/2)
data_D["expected_center_arm_y"] = expected_top_left_board_x - side_size/2 - point_arm_starting[0]
data_D["expected_center_arm_z"] = point_arm_starting[2]

data_D.tail(5)

bottom_left_pixel_x  bottom_left_pixel_y  top_left_pixel_x  \
90            1386.7900            680.21330         1403.0869   
91            1399.3282            694.07060         1401.8728   
92            1390.9973            686.17860         1403.6089   
93            1395.3796            689.80676         1399.3779   
94            1393.0947            686.96075         1403.0493   

    top_left_pixel_y  top_right_pixel_x  top_right_pixel_y  \
90          842.1241          1544.4453          834.84610   
91          843.4549          1556.1368          844.38550   
92          842.9651          1547.1604          836.20245   
93          845.8674          1554.5514          843.43494   
94          842.3679          1550.0833          839.76600   

    bottom_right_pixel_x  bottom_right_pixel_y  expected_top_left_board_x  \
90             1543.2697             693.43555                        4.4   
91             1541.8231             694.74567                        4.4   
92             1542.3191             693.51355                        4.4   
93             1537.4799             698.99426                        4.4   
94             1542.5555             693.73694                        4.4   

    expected_top_left_board_y          ...            \
90                       23.6          ...             
91                       23.6          ...             
92                       23.6          ...             
93                       23.6          ...             
94                       23.6          ...             

    expected_top_left_board_z  expected_bottom_left_board_z  \
90                        0.0                           0.0   
91                        0.0                           0.0   
92                        0.0                           0.0   
93                        0.0                           0.0   
94                        0.0                           0.0   

    expected_top_right_board_z  expected_bottom_right_board_z  \
90                         0.0                            0.0   
91                         0.0                            0.0   
92                         0.0                            0.0   
93                         0.0                            0.0   
94                         0.0                            0.0   

    expected_center_board_x  expected_center_board_y  expected_center_board_z  \
90                      2.2                     25.8                      0.0   
91                      2.2                     25.8                      0.0   
92                      2.2                     25.8                      0.0   
93                      2.2                     25.8                      0.0   
94                      2.2                     25.8                      0.0   

    expected_center_arm_x  expected_center_arm_y  expected_center_arm_z  
90                  -33.8                  -17.8                    0.0  
91                  -33.8                  -17.8                    0.0  
92                  -33.8                  -17.8                    0.0  
93                  -33.8                  -17.8                    0.0  
94                  -33.8                  -17.8                    0.0  

[5 rows x 26 columns]

In [3]:
data_C = pd.read_csv("dataQr/qrC.csv") 

point_E_top_left_board = (40.0, 23.6, 0.0)
side_size = 4.4
point_arm_starting = (20, -8, 0.0)

expected_top_left_board_x = point_E_top_left_board[0]
expected_top_left_board_y = point_E_top_left_board[1]

data_C["expected_top_left_board_x"] = expected_top_left_board_x
data_C["expected_top_left_board_y"] = expected_top_left_board_y
data_C["expected_bottom_left_board_x"] = expected_top_left_board_x
data_C["expected_bottom_left_board_y"] = expected_top_left_board_y + side_size
data_C["expected_top_right_board_x"] = expected_top_left_board_x - side_size
data_C["expected_top_right_board_y"] = expected_top_left_board_y
data_C["expected_bottom_right_board_x"] = expected_top_left_board_x - side_size
data_C["expected_bottom_right_board_y"] = expected_top_left_board_y + side_size


data_C["expected_top_left_board_z"] = point_E_top_left_board[2]
data_C["expected_bottom_left_board_z"] = point_E_top_left_board[2]
data_C["expected_top_right_board_z"] = point_E_top_left_board[2]
data_C["expected_bottom_right_board_z"] = point_E_top_left_board[2]

data_C["expected_center_board_x"] = expected_top_left_board_x - side_size/2
data_C["expected_center_board_y"] = expected_top_left_board_y + side_size/2
data_C["expected_center_board_z"] = point_E_top_left_board[2]

data_C["expected_center_arm_x"] = point_arm_starting[1] - (expected_top_left_board_y + side_size/2)
data_C["expected_center_arm_y"] = expected_top_left_board_x - side_size/2 - point_arm_starting[0]
data_C["expected_center_arm_z"] = point_arm_starting[2]

data_C.tail(5)

bottom_left_pixel_x  bottom_left_pixel_y  top_left_pixel_x  \
113            418.69928            682.94940         407.74414   
114            420.34180            685.87280         403.27875   
115            420.39542            687.86847         403.49225   
116            420.83160            685.91315         404.20294   
117            424.99880            691.00775         400.05720   

     top_left_pixel_y  top_right_pixel_x  top_right_pixel_y  \
113          830.7929          556.66736          833.37320   
114          834.5892          560.44385          835.84534   
115          835.2370          561.09640          832.96730   
116          834.4109          558.85706          834.29680   
117          837.6203          566.25950          840.93810   

     bottom_right_pixel_x  bottom_right_pixel_y  expected_top_left_board_x  \
113             569.93800             681.95630                       40.0   
114             567.04160             684.44080                       40.0   
115             565.02540             685.66580                       40.0   
116             566.40533             684.08655                       40.0   
117             564.43570             685.89680                       40.0   

     expected_top_left_board_y          ...            \
113                       23.6          ...             
114                       23.6          ...             
115                       23.6          ...             
116                       23.6          ...             
117                       23.6          ...             

     expected_top_left_board_z  expected_bottom_left_board_z  \
113                        0.0                           0.0   
114                        0.0                           0.0   
115                        0.0                           0.0   
116                        0.0                           0.0   
117                        0.0                           0.0   

     expected_top_right_board_z  expected_bottom_right_board_z  \
113                         0.0                            0.0   
114                         0.0                            0.0   
115                         0.0                            0.0   
116                         0.0                            0.0   
117                         0.0                            0.0   

     expected_center_board_x  expected_center_board_y  \
113                     37.8                     25.8   
114                     37.8                     25.8   
115                     37.8                     25.8   
116                     37.8                     25.8   
117                     37.8                     25.8   

     expected_center_board_z  expected_center_arm_x  expected_center_arm_y  \
113                      0.0                  -33.8                   17.8   
114                      0.0                  -33.8                   17.8   
115                      0.0                  -33.8                   17.8   
116                      0.0                  -33.8                   17.8   
117                      0.0                  -33.8                   17.8   

     expected_center_arm_z  
113                    0.0  
114                    0.0  
115                    0.0  
116                    0.0  
117                    0.0  

[5 rows x 26 columns]

In [4]:
data_F = pd.read_csv("dataQr/qrF.csv") 

point_E_top_left_board = (14.4, 7.6, 19.6)
side_size = 4.4
point_arm_starting = (20, -8, 0.0)

expected_top_left_board_x = point_E_top_left_board[0]
expected_top_left_board_y = point_E_top_left_board[1]

data_F["expected_top_left_board_x"] = expected_top_left_board_x
data_F["expected_top_left_board_y"] = expected_top_left_board_y
data_F["expected_bottom_left_board_x"] = expected_top_left_board_x
data_F["expected_bottom_left_board_y"] = expected_top_left_board_y + side_size
data_F["expected_top_right_board_x"] = expected_top_left_board_x - side_size
data_F["expected_top_right_board_y"] = expected_top_left_board_y
data_F["expected_bottom_right_board_x"] = expected_top_left_board_x - side_size
data_F["expected_bottom_right_board_y"] = expected_top_left_board_y + side_size


data_F["expected_top_left_board_z"] = point_E_top_left_board[2]
data_F["expected_bottom_left_board_z"] = point_E_top_left_board[2]
data_F["expected_top_right_board_z"] = point_E_top_left_board[2]
data_F["expected_bottom_right_board_z"] = point_E_top_left_board[2]

data_F["expected_center_board_x"] = expected_top_left_board_x - side_size/2
data_F["expected_center_board_y"] = expected_top_left_board_y + side_size/2
data_F["expected_center_board_z"] = point_E_top_left_board[2]

data_F["expected_center_arm_x"] = point_arm_starting[1] - (expected_top_left_board_y + side_size/2)
data_F["expected_center_arm_y"] = expected_top_left_board_x - side_size/2 - point_arm_starting[0]
data_F["expected_center_arm_z"] = point_arm_starting[2]

data_F.tail(5)

bottom_left_pixel_x  bottom_left_pixel_y  top_left_pixel_x  \
139            1228.6125           119.448550         1221.4362   
140            1217.6196           106.367180         1222.7911   
141            1218.8506           113.941710         1232.1337   
142            1220.7085           114.351160         1222.6727   
143            1217.4568           110.448265         1228.2416   

     top_left_pixel_y  top_right_pixel_x  top_right_pixel_y  \
139         330.83650          1450.7053          335.21290   
140         332.25480          1441.7424          329.64180   
141         324.01114          1447.1556          330.22467   
142         332.92640          1446.5781          330.19537   
143         328.15744          1445.6805          330.14197   

     bottom_right_pixel_x  bottom_right_pixel_y  expected_top_left_board_x  \
139             1441.7902            124.325660                       14.4   
140             1437.5314            127.995186                       14.4   
141             1447.6224            115.381980                       14.4   
142             1443.1937            121.210530                       14.4   
143             1445.5535            117.912680                       14.4   

     expected_top_left_board_y          ...            \
139                        7.6          ...             
140                        7.6          ...             
141                        7.6          ...             
142                        7.6          ...             
143                        7.6          ...             

     expected_top_left_board_z  expected_bottom_left_board_z  \
139                       19.6                          19.6   
140                       19.6                          19.6   
141                       19.6                          19.6   
142                       19.6                          19.6   
143                       19.6                          19.6   

     expected_top_right_board_z  expected_bottom_right_board_z  \
139                        19.6                           19.6   
140                        19.6                           19.6   
141                        19.6                           19.6   
142                        19.6                           19.6   
143                        19.6                           19.6   

     expected_center_board_x  expected_center_board_y  \
139                     12.2                      9.8   
140                     12.2                      9.8   
141                     12.2                      9.8   
142                     12.2                      9.8   
143                     12.2                      9.8   

     expected_center_board_z  expected_center_arm_x  expected_center_arm_y  \
139                     19.6                  -17.8                   -7.8   
140                     19.6                  -17.8                   -7.8   
141                     19.6                  -17.8                   -7.8   
142                     19.6                  -17.8                   -7.8   
143                     19.6                  -17.8                   -7.8   

     expected_center_arm_z  
139                    0.0  
140                    0.0  
141                    0.0  
142                    0.0  
143                    0.0  

[5 rows x 26 columns]

In [5]:
data_G = pd.read_csv("dataQr/qrG.csv") 

point_E_top_left_board = (19.4, 15.6, 9.8)
side_size = 4.4
point_arm_starting = (20, -8, 0.0)

expected_top_left_board_x = point_E_top_left_board[0]
expected_top_left_board_y = point_E_top_left_board[1]

data_G["expected_top_left_board_x"] = expected_top_left_board_x
data_G["expected_top_left_board_y"] = expected_top_left_board_y
data_G["expected_bottom_left_board_x"] = expected_top_left_board_x
data_G["expected_bottom_left_board_y"] = expected_top_left_board_y + side_size
data_G["expected_top_right_board_x"] = expected_top_left_board_x - side_size
data_G["expected_top_right_board_y"] = expected_top_left_board_y
data_G["expected_bottom_right_board_x"] = expected_top_left_board_x - side_size
data_G["expected_bottom_right_board_y"] = expected_top_left_board_y + side_size


data_G["expected_top_left_board_z"] = point_E_top_left_board[2]
data_G["expected_bottom_left_board_z"] = point_E_top_left_board[2]
data_G["expected_top_right_board_z"] = point_E_top_left_board[2]
data_G["expected_bottom_right_board_z"] = point_E_top_left_board[2]

data_G["expected_center_board_x"] = expected_top_left_board_x - side_size/2
data_G["expected_center_board_y"] = expected_top_left_board_y + side_size/2
data_G["expected_center_board_z"] = point_E_top_left_board[2]

data_G["expected_center_arm_x"] = point_arm_starting[1] - (expected_top_left_board_y + side_size/2)
data_G["expected_center_arm_y"] = expected_top_left_board_x - side_size/2 - point_arm_starting[0]
data_G["expected_center_arm_z"] = point_arm_starting[2]

data_G.tail(5)

bottom_left_pixel_x  bottom_left_pixel_y  top_left_pixel_x  \
309            989.83905            401.94855         995.25287   
310            992.67865            402.77030         992.49920   
311            992.41846            403.04680         990.98790   
312            990.72970            401.49368         988.60510   
313            997.44530            406.57483         995.15125   

     top_left_pixel_y  top_right_pixel_x  top_right_pixel_y  \
309         579.09330          1165.7173           575.9286   
310         578.99980          1164.9908           576.6740   
311         580.84240          1166.5675           576.8078   
312         585.03180          1164.4619           575.2342   
313         579.30634          1167.9883           579.9941   

     bottom_right_pixel_x  bottom_right_pixel_y  expected_top_left_board_x  \
309             1168.3625             407.24048                       19.4   
310             1167.0602             410.29816                       19.4   
311             1167.4696             409.87100                       19.4   
312             1163.9050             411.80536                       19.4   
313             1165.9402             409.23060                       19.4   

     expected_top_left_board_y          ...            \
309                       15.6          ...             
310                       15.6          ...             
311                       15.6          ...             
312                       15.6          ...             
313                       15.6          ...             

     expected_top_left_board_z  expected_bottom_left_board_z  \
309                        9.8                           9.8   
310                        9.8                           9.8   
311                        9.8                           9.8   
312                        9.8                           9.8   
313                        9.8                           9.8   

     expected_top_right_board_z  expected_bottom_right_board_z  \
309                         9.8                            9.8   
310                         9.8                            9.8   
311                         9.8                            9.8   
312                         9.8                            9.8   
313                         9.8                            9.8   

     expected_center_board_x  expected_center_board_y  \
309                     17.2                     17.8   
310                     17.2                     17.8   
311                     17.2                     17.8   
312                     17.2                     17.8   
313                     17.2                     17.8   

     expected_center_board_z  expected_center_arm_x  expected_center_arm_y  \
309                      9.8                  -25.8                   -2.8   
310                      9.8                  -25.8                   -2.8   
311                      9.8                  -25.8                   -2.8   
312                      9.8                  -25.8                   -2.8   
313                      9.8                  -25.8                   -2.8   

     expected_center_arm_z  
309                    0.0  
310                    0.0  
311                    0.0  
312                    0.0  
313                    0.0  

[5 rows x 26 columns]

In [6]:
data = data_E.append(data_D)
data = data.append(data_C)
data = data.append(data_F)
data = data.append(data_G)
print(len(data_E), len(data_D), len(data_C), len(data_F), len(data_G))
print("len(sum of datasets): ", len(data_E) + len(data_D) + len(data_C) + len(data_F) + len(data_G), ", len(data): ", len(data))

144 95 118 144 314
len(sum of datasets):  815 , len(data):  815


In [7]:
# X = [[500., 100., 400, 100, 500, 50, 400, 50], [1500., 110., 1400, 110, 1500, 150, 1400, 150], [1500., 110., 1400, 110, 1500, 150, 1400, 150], [1500., 110., 1400, 110, 1500, 150, 1400, 150]]
# y = [[0.45, 0.075],[1.45, 0.130],[1.45, 0.130],[1.45, 0.130]]
# X_train = X[:-2]
# X_test = X[-2:]
# y_train = y[:-2]
# y_test = y[-2:]

In [8]:
def shuffle(df, axis=1):
    df = df.copy()
#     n = len(df)
    n = 10
    for _ in range(n):
        df.apply(np.random.shuffle, axis=axis)
    return df

In [9]:
shuffled_data = data.copy()

X = shuffled_data[["bottom_left_pixel_x","bottom_left_pixel_y","top_left_pixel_x","top_left_pixel_y","top_right_pixel_x","top_right_pixel_y","bottom_right_pixel_x","bottom_right_pixel_y"]]
y = shuffled_data[["expected_center_arm_x", "expected_center_arm_y", "expected_center_arm_z"]]

held_out_percent = 0.01
held_out_count = int(len(data) * held_out_percent)
X_train = X[:-held_out_count]
X_test = X[-held_out_count:]
y_train = y[:-held_out_count]
y_test = y[-held_out_count:]

In [10]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
# Create linear regression object
regr = linear_model.LinearRegression()

regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
# Make predictions using the testing set
y_pred = regr.predict(X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

# # Plot outputs
# plt.scatter(X_test, y_test,  color='black')
# plt.plot(X_test, y_pred, color='blue', linewidth=3)

# plt.xticks(())
# plt.yticks(())

# plt.show()
print(y_test[:-1].astype(int), y_pred[:-1].astype(int))
print(y_test[-1:].astype(int), y_pred[-1:].astype(int))

Coefficients: 
 [[-0.00495686  0.02846222 -0.01966148 -0.07533031  0.03249878 -0.0230031
  -0.00775042  0.03405114]
 [-0.04935309  0.03204813 -0.07239341 -0.09310723  0.05751821  0.03899852
   0.02844423  0.02061931]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]]
Mean squared error: 0.07
Variance score: 0.33
     expected_center_arm_x  expected_center_arm_y  expected_center_arm_z
306                    -25                     -2                      0
307                    -25                     -2                      0
308                    -25                     -2                      0
309                    -25                     -2                      0
310                    -25                     -2                      0
311                    -25                     -2                      0
312                    -25                     -2                      0 [[-25  -2   0]
 [-25  -2   0]
 [-25  -2   0]
 [-25  -2   0]

In [12]:
X_test

bottom_left_pixel_x  bottom_left_pixel_y  top_left_pixel_x  \
306            993.83374            403.47443         993.41925   
307            992.27280            403.38412         986.11700   
308            992.25290            402.72513         993.69604   
309            989.83905            401.94855         995.25287   
310            992.67865            402.77030         992.49920   
311            992.41846            403.04680         990.98790   
312            990.72970            401.49368         988.60510   
313            997.44530            406.57483         995.15125   

     top_left_pixel_y  top_right_pixel_x  top_right_pixel_y  \
306         579.69604          1164.1799          575.86050   
307         584.03595          1166.5266          576.26310   
308         578.93730          1166.8180          577.83514   
309         579.09330          1165.7173          575.92860   
310         578.99980          1164.9908          576.67400   
311         580.84240          1166.5675          576.80780   
312         585.03180          1164.4619          575.23420   
313         579.30634          1167.9883          579.99410   

     bottom_right_pixel_x  bottom_right_pixel_y  
306             1166.3650             410.02472  
307             1164.7084             414.16794  
308             1168.5411             408.03702  
309             1168.3625             407.24048  
310             1167.0602             410.29816  
311             1167.4696             409.87100  
312             1163.9050             411.80536  
313             1165.9402             409.23060

In [13]:
from sklearn.neural_network import MLPRegressor
clf = MLPRegressor(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(40, 30, 10, 25), random_state=1)
clf.fit(X_train, y_train)

MLPRegressor(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(40, 30, 10, 25), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [14]:
y_pred = clf.predict(X_test)
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
print(y_test[:-1].astype(int), y_pred[:-1].astype(int))
print(y_test[-1:].astype(int), y_pred[-1:].astype(int))

Mean squared error: 0.04
     expected_center_arm_x  expected_center_arm_y  expected_center_arm_z
306                    -25                     -2                      0
307                    -25                     -2                      0
308                    -25                     -2                      0
309                    -25                     -2                      0
310                    -25                     -2                      0
311                    -25                     -2                      0
312                    -25                     -2                      0 [[-25  -2   0]
 [-25  -2   0]
 [-25  -2   0]
 [-25  -2   0]
 [-25  -3   0]
 [-25  -2   0]
 [-25  -2   0]]
     expected_center_arm_x  expected_center_arm_y  expected_center_arm_z
313                    -25                     -2                      0 [[-25  -2   0]]


In [15]:
class timeit():
    from datetime import datetime
    def __enter__(self):
        self.tic = self.datetime.now()
    def __exit__(self, *args, **kwargs):
        print('runtime: {}'.format(self.datetime.now() - self.tic))

In [16]:
from datetime import datetime
datetime.now()

datetime.datetime(2019, 5, 3, 12, 45, 4, 4072)

In [17]:
# regr.predict([1395.1582,690.2671,1404.3729,840.06885,1554.4364,843.0976,1544.1744,692.78174])
X_validate = [
    [1395.1582,690.2671,1404.3729,840.06885,1554.4364,843.0976,1544.1744,692.78174],
    [425.08948,688.82007,400.65857,837.42413,562.5942,840.0118,563.503,687.0966],
    [861.4465,221.13101,856.76025,351.2697,996.6109,354.29453,997.3974,216.82195],
    [1216.8048,108.742096,1221.4166,332.99548,1443.5278,328.23065,1445.7577,120.2978],
    [989.15936,398.22433,998.178,576.02185,1162.1074,574.61816,1170.0554,406.4485]
]
y_validate = [[-33.8,-17.8,0.0],
[-33.8,17.8,0.0],
[-15.8,2.2,0.0],
[-17.8,-7.8,0.0],
[-25.8,-2.8,0.0]]

with timeit():
    k = datetime.now()
    pred_clf = clf.predict(X_validate)
print(pred_clf)    
with timeit():
    pred_regr = regr.predict(X_validate)
print(pred_regr)    
print(y_validate)

runtime: 0:00:00.000999
[[-33.99816332 -17.71687527  -0.33169372]
 [-33.53669213  17.80110362  -0.36866139]
 [-15.82128093   2.05516208  -0.30505947]
 [-17.78717723  -8.1360653    0.27308466]
 [-25.7549932   -2.92916086   0.08342121]]
runtime: 0:00:00
[[-33.86116521 -17.7867307    0.        ]
 [-33.91576859  17.77033776   0.        ]
 [-15.8339028    2.15860688   0.        ]
 [-18.22521642  -8.22612433   0.        ]
 [-25.7084841   -2.70022081   0.        ]]
[[-33.8, -17.8, 0.0], [-33.8, 17.8, 0.0], [-15.8, 2.2, 0.0], [-17.8, -7.8, 0.0], [-25.8, -2.8, 0.0]]


Save/load linear and MPL regressors from disk:

In [18]:
from sklearn import model_selection
from sklearn.externals import joblib

filename = 'pixels_qr_MLPRegressor_xyz.sav'
joblib.dump(clf, filename)

filename = 'pixels_qr_LinearRegressor_xyz.sav'
joblib.dump(regr, filename)

with timeit():
    loaded_clf = joblib.load('pixels_qr_MLPRegressor_xyz.sav')
    pred_clf = loaded_clf.predict(X_validate)
print(pred_clf)    
with timeit():
    loaded_regr = joblib.load('pixels_qr_LinearRegressor_xyz.sav')
    pred_regr = loaded_regr.predict(X_validate)
print(pred_regr)    
print(y_validate)

runtime: 0:00:00.000999
[[-33.99816332 -17.71687527  -0.33169372]
 [-33.53669213  17.80110362  -0.36866139]
 [-15.82128093   2.05516208  -0.30505947]
 [-17.78717723  -8.1360653    0.27308466]
 [-25.7549932   -2.92916086   0.08342121]]
runtime: 0:00:00.000999
[[-33.86116521 -17.7867307    0.        ]
 [-33.91576859  17.77033776   0.        ]
 [-15.8339028    2.15860688   0.        ]
 [-18.22521642  -8.22612433   0.        ]
 [-25.7084841   -2.70022081   0.        ]]
[[-33.8, -17.8, 0.0], [-33.8, 17.8, 0.0], [-15.8, 2.2, 0.0], [-17.8, -7.8, 0.0], [-25.8, -2.8, 0.0]]
